--- 
- name: Ansible install apache server 
  hosts: worker1
  tasks:
    - name: packages | ensure apt list dir exists
      file:
        path: /var/lib/apt/lists/
        state: directory
        mode: 0755

    - name: Install Apache
      apt:
        name: apache2 
        update_cache: yes 
        state: latest

    - name: install ansible
      apt: name=ansible update_cache=yes state=latest

