- hosts: all
  become: false
  tasks:
    - name: install apache
      apt: 
        name: apache2 
        update_cache: yes 
        state: latest

    - name: install ansible
      apt: name=ansible update_cache=yes state=latest

